KMAXX/Controllers/currentAffairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KMAXX.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace KMAXX.Controllers
{
    public class currentAffairsController : Controller
    {
        // GET: currentAffairs

        public ActionResult Index(string mode)
        {
            if (User.IsInRole("admin"))
            {
                
                return RedirectToAction("forAdmin",new { mode = mode});
            }
            else if (User.IsInRole("user"))
            {
               // TempData["modes"] = mode;
                return RedirectToAction("Download", new { mode = mode });
            }
            else
            {
                ViewBag.returnUrl = mode;
                return View("loginrequired");
            }
        }


        public ActionResult upload()
        {
            var model = new MyViewModel();
            return View(model);
        }

        #region insert files to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addfile(MyViewModel model, string mode)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.success = "File should be in PDF format and Size should be less than 5 mb";
                return View();
            }
            if (ModelState.IsValid)
            {
                if (model.File != null)
                {
                    FileUploadDBModel fileUploadModel = new FileUploadDBModel();

                    byte[] uploadFile = new byte[model.File.InputStream.Length];
                    model.File.InputStream.Read(uploadFile, 0, uploadFile.Length);

                    fileUploadModel.FileName = model.File.FileName;
                    fileUploadModel.File = uploadFile;
                    // fileUploadModel.exam = model.exam;
                    try
                    {
                        using (SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                        {
                            using (SqlCommand cmd = new SqlCommand("insert into quspapers values(@name, @type, @data,@exam,@date)", connection))
                            {
                                connection.Open();
                                cmd.Parameters.Add("@name", SqlDbType.VarChar).Value = fileUploadModel.FileName;
                                cmd.Parameters.Add("@type", SqlDbType.VarChar).Value = model.File.ContentType;
                                cmd.Parameters.Add("@data", SqlDbType.Binary).Value = uploadFile;
                                cmd.Parameters.Add("@exam", SqlDbType.VarChar).Value = mode;
                                cmd.Parameters.Add("@date", SqlDbType.DateTime).Value = DateTime.Now;
                                cmd.ExecuteNonQuery();
                            }
                            connection.Close();
                        }
                    }
                    catch (Exception)
                    {
                        ViewBag.sta = "Error in uplading file";
                    }
                   
                }
                else
                {
                    ViewBag.sta = "File not selected";
                }
            }
            //else {
            //    HttpPostedFileBase upload = Request.Files["File"];
            //    if (upload.ContentLength == 0)
            //    {
            //        ModelState.AddModelError("File", "Please upload file");
            //    }
            //    else if (upload.ContentLength > 0)
            //    {
            //        string filename = upload.FileName;
            //        string type = upload.ContentType;
            //        byte[] temp = new byte[upload.ContentLength];
            //        var data = upload.InputStream.Read(temp,0,Convert.ToInt16(upload.ContentLength));
            //        var types = MVCSecurity.Filters
            //    }

            //}
          
            // SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString);
            //query = "insert into PDFFiles (Name,type,data)" + " values (@Name, @type, @Data)";   //insert query
            // SqlCommand com = new SqlCommand("insert into PDFFiles (Name,type,data)" + " values (@Name, @type, @Data)", con);

            return RedirectToAction("Index",new {mode = mode });
        }
        #endregion

        #region download files from db
        public ActionResult Download(string mode)
        {
            // string mode = TempData["modes"].ToString();
            if (mode != null && mode != "")
            {
                if (mode == "qusPaper")
                { ViewBag.st = true; }

                List<FileUploadDBModel> obj = new List<FileUploadDBModel>();
                obj = toGetFiles(mode);
                return View(obj);

            }
            else { return View("error");

            }
        }

        #endregion

        #region to get files from db
        public List<FileUploadDBModel> toGetFiles(string mode)
        {
            List<FileUploadDBModel> obj = new List<FileUploadDBModel>();
            DataSet ds = new DataSet();
            try {
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand("select * from quspapers where exam = @mode", con))
                    {
                        con.Open();
                        cmd.Parameters.AddWithValue("@mode", mode);
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        da.Fill(ds);
                        for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                        {
                            FileUploadDBModel uobj = new FileUploadDBModel();
                            uobj.Id = Convert.ToInt16(ds.Tables[0].Rows[i]["id"]);
                            uobj.FileName = ds.Tables[0].Rows[i]["name"].ToString();
                            uobj.Type = ds.Tables[0].Rows[i]["type"].ToString();
                            uobj.File = (byte[])(ds.Tables[0].Rows[i]["data"]);
                            uobj.lastupdated = Convert.ToDateTime(ds.Tables[0].Rows[i]["lastupdated"]);
                            obj.Add(uobj);
                        }
                        // obj.OrderByDescending(x => x.lastupdated);
                        obj = obj.OrderByDescending(x => x.lastupdated).ToList();
                    }
                    con.Close();
                }
            }
            catch(Exception) {
                return null;
            }
           
            return obj;
        }
        #endregion

        #region download file
        public FileContentResult FileDownload(int? id)
        {
            byte[] fileData = { };
            string fileName = "";
            DataSet ds = new DataSet();
            try {
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand("select * from quspapers where id=@id", con))
                    {
                        con.Open();
                        cmd.Parameters.Add("@id", SqlDbType.Int).Value = id;
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        da.Fill(ds);

                        for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                        {
                            FileUploadDBModel uobj = new FileUploadDBModel();
                            uobj.Id = Convert.ToInt16(ds.Tables[0].Rows[i]["id"]);
                            fileName = ds.Tables[0].Rows[i]["name"].ToString();
                            uobj.Type = ds.Tables[0].Rows[i]["type"].ToString();
                            fileData = (byte[])(ds.Tables[0].Rows[i]["data"]);
                        }
                    }
                    con.Close();

                    return File(fileData, "text", fileName);
                }
            }
            catch(Exception) {
                return File(fileData,"text");
            }
           
        }
        #endregion

        #region admin
        public ActionResult forAdmin(string mode)
        {
            // string mode = TempData["modes"].ToString();
            //List<FileUploadDBModel> fileList = new List<FileUploadDBModel>();
            try {
                ViewBag.files = toGetFiles(mode);
                ViewBag.mode = mode;
            }
            catch(Exception) {
                return View("error");
            }
           
            return View("upload");
        }
        #endregion
        public ActionResult publication()
        {
            return View();
        }
        
    }

}

KMAXX/Views/currentAffairs/Download.cshtml
<div>
    @{Html.RenderPartial("_fileList");}
</div>

KMAXX/Views/currentAffairs/addfile.cshtml
<div class="jumbotron" style="background-color:white;opacity:.9">
    <h2>Error : @ViewBag.success</h2>
</div>

KMAXX/Views/currentAffairs/forAdmin.cshtml
<div>
    @{Html.RenderPartial("_fileList");}
</div>
<div>
    @{Html.RenderPartial("_uploadFile");}
</div>

KMAXX/Views/currentAffairs/publication.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        .pub {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 5px;
            width: 150px;
        }

            img:hover {
                box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
            }
    </style>
</head>
<body>
    <div  style="background-color:antiquewhite;opacity:.9;padding-left:30px">
        <br/>
        <a  target="_blank" href="~/Content/Images/1.jpg">
            <img class="pub" src="~/Content/Images/1.jpg" alt="Kmaxx" style="width:200px">
        </a>
        <a  target="_blank" href="~/Content/Images/2.jpg">
            <img class="pub" src="~/Content/Images/2.jpg" alt="Kmaxx" style="width:200px">
        </a>
        <a  target="_blank" href="~/Content/Images/3.jpg">
            <img class="pub" src="~/Content/Images/3.jpg" alt="Kmaxx" style="width:200px">
        </a>
        <a target="_blank" href="~/Content/Images/4.jpg">
            <img class="pub" src="~/Content/Images/4.jpg" alt="Kmaxx" style="width:200px">
        </a>
        <br />
        <br />
    </div>
       

</body>
</html>

KMAXX/Views/currentAffairs/upload.cshtml
@model KMAXX.Models.MyViewModel


<style>

    th {
    color:black;
    }
</style>

<div class="jumbotron" style="background-color:white;opacity:0.9">
    <p><button class="btn btn-default pull-right" onclick="location.href='@Url.Action("allusers","Home")'"> Click here to view all the users </button>
     <button class="btn btn-default pull-right" onclick="location.href='@Url.Action("Approve","Home")'"> Click here to approve the request </button></p>
    @using (Html.BeginForm("addfile", "currentAffairs", new { mode = ViewBag.mode }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div>
            @Html.LabelFor(x => x.File)
            @Html.TextBoxFor(x => x.File, new { type = "file" })
            @Html.ValidationMessageFor(x => x.File)
        </div>
        <br />
        <button class="btn-default" type="submit">Upload File</button>
    }
    <br/>
   
   
           <p style="color:black">err @ViewBag.success</p>
        

    @*<p>
        @Html.ActionLink("Download File", "Download")
    </p>*@
    <table class="table">
        <tr>
            <th style="color:black">
                File
            </th>
            <th style="color:black">
                Download
            </th>
        </tr>

        @foreach (var item in ViewBag.files)
        {
            int id;
            <tr>
                <td>
                    @item.FileName
                </td>
                <td>
                    @Html.ActionLink("Download", "Filedownload", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
    @ViewBag.sta
</div>
<script>

    $(function () {
        jQuery.validator.unobtrusive.adapters.add('filesize', ['maxbytes'], function (options) {
            // Set up test parameters
            var params = {
                maxbytes: options.params.maxbytes
            };

            // Match parameters to the method to execute
            options.rules['filesize'] = params;
            if (options.message) {
                // If there is a message, set it for the rule
                options.messages['filesize'] = options.message;
            }
        });

        jQuery.validator.addMethod("filesize", function (value, element, param) {
            if (value === "") {
                // no file supplied
                return true;
            }

            var maxBytes = parseInt(param.maxbytes);

            // use HTML5 File API to check selected file size
            // https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications
            // http://caniuse.com/#feat=fileapi
            if (element.files != undefined && element.files[0] != undefined && element.files[0].size != undefined) {
                var filesize = parseInt(element.files[0].size);

                return filesize <= maxBytes;
            }

            // if the browser doesn't support the HTML5 file API, just return true
            // since returning false would prevent submitting the form 
            return true;
        });
    }(jQuery)); 
</script>