KMAXX/Controllers/BatchDetailsController.cs
using KMAXX.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace KMAXX.Controllers
{
    public class BatchDetailsController : Controller
    {
        // GET: BatchDetails
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult updateDetails()
        {
            if (User.IsInRole("admin"))
            {

                ViewBag.admin = true;

            }
            List<batchDetails> list = new List<batchDetails>();
            list = getBatchDetails();
            if (list != null && list.Count > 0)
            {
                ViewBag.get = true;
                batch obj = new batch();
                obj.BatchDetails = list;
                return View(obj);
            }
            else
            {
                ViewBag.get = false;
                //ModelState.AddModelError("testSub", "Subject not found");
                //ModelState.AddModelError("testDate", "Date not found ");
                return View();
            }
       
        }
        public List<batchDetails> getBatchDetails()
        {
            List<batchDetails> userlist = new List<batchDetails>();
            test obj = new test();
            DataSet ds = new DataSet();
            try {
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand("select * from batchDetails", con))
                    {
                        con.Open();
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        da.Fill(ds);

                        for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                        {
                            batchDetails uobj = new batchDetails();
                            uobj.course = ds.Tables[0].Rows[i]["course"].ToString();
                            uobj.startsOn = Convert.ToDateTime(ds.Tables[0].Rows[i]["startsOn"]);
                            uobj.session = ds.Tables[0].Rows[i]["session"].ToString();

                            userlist.Add(uobj);

                        }
                        con.Close();
                        userlist = userlist.OrderByDescending(x => x.startsOn).ToList();
                        if (userlist.Count > 0 && userlist != null)
                        {
                            return userlist;
                        }
                        else
                        {
                            return null;
                        }

                    }

                }
            }
            catch(Exception)
            {
                return null;
            }
            
        }
        public ActionResult updateBatch(List<batchDetails> model)
        {
            return View();
        }
        [WebMethod]
        [HttpPost]
        public ActionResult SaveData(string emp)//WebMethod to Save the data  
        {
            try {
                if (emp == null || emp == "[]")
                {

                    return Json(new { error = true, responseText = "Please Check Values", Url = "updateDetails" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var json = Request.RequestContext.HttpContext.Request.Params["emp"];
                    var format = "yyyy-mm-dd"; // your datetime format
                                               //var dateTimeConverter = new IsoDateTimeConverter { DateTimeFormat = format };

                    List<batchDetails> serializeData = JsonConvert.DeserializeObject<List<batchDetails>>(emp);
                    if (serializeData != null && serializeData.Count() > 0)
                    {
                        using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                        {
                            foreach (var data in serializeData)
                            {
                                DateTime date = Convert.ToDateTime(DateTime.Parse(data.startsOn.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture)));

                                if (date >= DateTime.Now)
                                {
                                    using (var cmd = new SqlCommand("INSERT INTO batchdetails VALUES(@course,@startsOn,@session)"))
                                    {
                                        cmd.CommandType = CommandType.Text;
                                        cmd.Parameters.AddWithValue("@course", data.course);
                                        cmd.Parameters.AddWithValue("@startsOn", data.startsOn.ToShortDateString());
                                        cmd.Parameters.AddWithValue("@session", data.session);
                                        cmd.Connection = con;
                                        if (con.State == ConnectionState.Closed)
                                        {
                                            con.Open();
                                        }
                                        cmd.ExecuteNonQuery();
                                        con.Close();
                                    }
                                }
                                else
                                {
                                    return Json(new { success = false, responseText = "Date should be today or future", Url = "updateDetails" }, JsonRequestBehavior.AllowGet);
                                }

                            }
                        }

                    }
                    else
                    {
                        return Json(new { error = true, responseText = "Please check the date and subject", Url = "updateDetails" }, JsonRequestBehavior.AllowGet);
                    }
                    // return Json(new { success = true, responseText = "Please check the date and subject", Url = "updateDetails" });
                    return Json(new { success = true, responseText = "Successfully Updated", Url = "updateDetails" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return Json(new { error = true, responseText = "Please Check Values", Url = "updateDetails" }, JsonRequestBehavior.AllowGet);
            }
            
        }
    }
}

KMAXX/Controllers/TestPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KMAXX.Models;
using System.Data;
using System.Data.SqlClient;
using Newtonsoft.Json;
using System.Web.Services;
using Newtonsoft.Json.Converters;
using System.Globalization;
using System.Configuration;

namespace KMAXX.Controllers
{
    public class TestPlanController : Controller
    {
        // GET: TestPlan
        //[ValidateAntiForgeryToken]
        public ActionResult testdate()
        {
            if (User.IsInRole("admin"))
            {

                ViewBag.admin = true;
                
            }
            List<testList> list = new List<testList>();
            list = getTestList();
            if ( list != null && list.Count > 0)
            {
                ViewBag.getdata = true;
                test obj = new test();
                obj.testDetails = list;
                return View(obj);
            }
            else
            {
                ViewBag.getdata = false;
                return View();
            }
        }
        public List<testList> getTestList()
        {
            List<testList> userlist = new List<testList>();
            test obj = new test();
            DataSet ds = new DataSet();
            try {
                using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand("select * from testlist", con))
                    {
                        con.Open();
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        da.Fill(ds);

                        for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                        {
                            testList uobj = new testList();
                            uobj.testSub = ds.Tables[0].Rows[i]["subject"].ToString();
                            uobj.testDate = Convert.ToDateTime(ds.Tables[0].Rows[i]["date"]);
                            if (uobj.testDate > DateTime.Now)
                            {
                                userlist.Add(uobj);
                            }
                        }
                        con.Close();
                        userlist = userlist.OrderByDescending(x => x.testDate).ToList();
                        if (userlist.Count > 0 && userlist != null)
                        {
                            return userlist;
                        }
                        else
                        {
                            return null;
                        }

                    }

                }
            }
            catch(Exception) {
                return null;
            }
            
        }
        public ActionResult addtest()
        {

            return View();
        }
        [WebMethod]
        [HttpPost]
        public ActionResult add(List<testList> list)
        {

            return View();
        }
        [WebMethod]
        [HttpPost]
        public ActionResult SaveData(string emp)//WebMethod to Save the data  
        {
            try
            {
                if (emp == null || emp == "[]")
                {

                    return Json(new { success = false, responseText = "Please Check Values" }, JsonRequestBehavior.AllowGet);
                }
                else
                {

                    var json = Request.RequestContext.HttpContext.Request.Params["emp"];
                    var format = "yyyy-mm-dd"; // your datetime format
                                               //var dateTimeConverter = new IsoDateTimeConverter { DateTimeFormat = format };
                    var serializeData = JsonConvert.DeserializeObject<List<testList>>(emp);
                    if (serializeData != null && serializeData.Count() > 0)
                    {
                        using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["kmaxxConString"].ConnectionString))
                        {
                            foreach (var data in serializeData)
                            {
                                DateTime date = Convert.ToDateTime(DateTime.Parse(data.testDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture)));
                                if (date != null && date >= DateTime.Now)
                                {
                                    using (var cmd = new SqlCommand("INSERT INTO testlist VALUES(@sub,@date)"))
                                    {
                                        cmd.CommandType = CommandType.Text;
                                        cmd.Parameters.AddWithValue("@sub", data.testSub);
                                        cmd.Parameters.AddWithValue("@date", data.testDate);
                                        cmd.Connection = con;
                                        if (con.State == ConnectionState.Closed)
                                        {
                                            con.Open();
                                        }
                                        cmd.ExecuteNonQuery();
                                        con.Close();
                                    }
                                }
                                else
                                {
                                    return Json(new { success = false, responseText = "Date should be today or future" }, JsonRequestBehavior.AllowGet);
                                }

                            }
                        }

                    }
                    else
                    {
                        return Json(new { success = false, responseText = "Please check the date and subject" }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { success = true, responseText = "Successfully Updated", Url = "testdate" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return Json(new { success = false, responseText = "Please Check Values" }, JsonRequestBehavior.AllowGet);
            }
           
        }
        public ActionResult YearPlan()
        {

            return View(); }
    }
    
}

KMAXX/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

KMAXX/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

KMAXX/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/ico" href="~/tit1.png" />
    <link rel="icon" type="image/ico" href="~/tit1.png" />
    <link rel="apple-touch-icon" type="image/ico" href="~/tit1.png" />
    <title>@ViewBag.Title - K-Maxx</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kalam' rel='stylesheet'>
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />


    <style>
        body {
            
            background-image: url('../../Content/Images/background_news.jpg');
           
        }
        /* layout */


        .navbar-right {
            position: relative;
            right: 120px;
        }

        .navbar-default .navbar-nav > li > a {
            color: #800000;
        }

        .navbar-default {
            border-color: black;
            background-color: #800000;
        }

        h4::first-letter {
            font-size: 40px;
        }

        .apps {
            font-weight: 600;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            padding-bottom: 30px;
            color: #8A2BE2;
        }

        .navbar-default .navbar-nav > li > a:hover,
        .navbar-default .navbar-nav > li > a:focus {
            color: orange;
        }
        .navbar-toggle:focus {
        background-color:#00ace6;
        }
       @@media screen and (max-width : 1920px){
  .div-only-mobile{
  visibility:hidden;
  }
}
@@media screen and (max-width : 906px){
 .desk{
  visibility:hidden;
  }
 .div-only-mobile{
  visibility:visible;
  }
}
    </style>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60" oncontextmenu="return false;">
    <nav class="navbar navbar-default navbar-fixed-top" style="align-content:center; background-image:url('../../Content/Images/bb4.jpg')">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#hidecontact" >Contact Us</button>
                <p  style="color:#800000">
                    <div id="contact" class="collapse navbar-collapse" >
                     <span class="glyphicon glyphicon-envelope"></span> kmaxxtnpsckanchi@gmail.com  &nbsp;<span class="glyphicon glyphicon-phone"></span> +91 8681888575<span class="glyphicon glyphicon-phone"></span> +91 9444544040<span><a href="https://www.facebook.com/groups/369361143258615/" target="_blank"> <img src="~/Content/Images/if_social-facebook-square2_771366.png" /></a> &nbsp;<a href="http://kmaxxtnpsc.blogspot.in/" target="_blank"> <img src="~/Content/Images/if_blogger_312520.png" /></a></span></div>
</p>
            </div>
            <div id="hidecontact" class="collapse">
                <ul class="nav navbar-nav">
                    <li>kmaxxtnpsckanchi@gmail.com </li>
                    <li>+91 8681888575</li>
                    <li>+91 9444544040</li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Course", "Course", "Course")</li>
                    <li>@Html.ActionLink("Batch Details", "updateDetails", "BatchDetails")</li>
                    <li class="dropdown">

                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Calendar", "Calendar")">Calendar <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Test Plan", "testdate", "TestPlan")</li>
                            <li>@Html.ActionLink("Year Plan", "YearPlan", "TestPlan")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Artifacts", "Artifacts")">Student's Corner <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Our Publications", "publication", "currentAffairs")</li>
                            <li>@Html.ActionLink("Question Paper", "Index", "currentAffairs", new { mode = "qusPaper" }, null)</li>
                            <li>@Html.ActionLink("Current Affairs", "Index", "currentAffairs", new { mode = "currentAffairs" }, null)</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Gallery", "Gallery", "Home")</li>
                    @if (HttpContext.Current.Session["UserID"] != null && HttpContext.Current.Session["UserID"].ToString() != "")
                    {
                        <li>@Html.ActionLink("LogOut", "LogOff", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>
                    }
                </ul>
            </div>

        </div>

    </nav>
    <div class="text-center" style="background-color:aliceblue;opacity:.9">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-4">
                    <br/>
                    <img src="~/Content/Images/final2.png" style="background-color:transparent;height:150px;width:300px"  />
                </div>
                <div class="col-xs-4 text-center">
                    <br/>
                    <span style="font-size: 23px;color:#001a00;" class="apps">Knowledge</span>&nbsp;<span style="font-size: 23px;color:#001a00; padding-left:10px" class="apps">Maths</span>&nbsp;<span style="font-size: 23px;color:#001a00; " class="apps">Aptitude</span>&nbsp;<span style="font-size: 23px;color:#001a00; " class="apps">Xcellence</span>&nbsp;<span style="font-size: 23px;color:#001a00;" class="apps">Xperience</span>&nbsp;<br /> <span style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;padding-left:30px; font-size:23px;color:#4d1f00;">TNPSC/TET Coaching Centre</span><br/><span style="font-size:23px;color:#4d1f00;font-weight:bold">Kanchipuram</span>
                    @*<h4 class="text-capitalize">Knowledge <span class="text-capitalize">Aptitude</span>  Xcellence Xperience</h4> <h3>TNPSC/TET Coaching Institute</h3>*@
                    
                    
                </div>
                <br/>
                <div class="col-xs-4">
                    <img src="~/Content/Images/book.gif" style="background-color:transparent" height="140" width="200" />
@if (ViewBag.admin == true)
{
                    <p style="color:black">visitors: @ApplicationInstance.Application["Totaluser"]</p>
}
                </div>
            </div>
        </div>

    </div>
    <div class="container">   
        <br/>    
        @RenderBody()      
    </div>
    @{Html.RenderPartial("_footer");}
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KMAXX/Views/Shared/_fileList.cshtml
@model IEnumerable<KMAXX.Models.FileUploadDBModel>

<div class="jumbotron" style="background-color:white;opacity:.9">
    @{ if (ViewBag.st == true)
        {

            <div><a href="http://www.tnpsc.gov.in/previous-questions.html" target="_blank">Click here to download TNPSC Exam Previous Year Question Paper</a></div>
            <br/>
            <div><h3>Question Papers</h3></div>
            <div>Students can download the question papers of weekly exams</div>
        }
        else
        {
            <div><h3>Current Affairs</h3></div>
            <div>Students can download the current affairs </div>
        }
    }
    <br/>
    Click on download Link to download files
    <br />
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.File)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            int id;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.ActionLink("Download", "Filedownload", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>

KMAXX/Views/Shared/_testDetail.cshtml
@model KMAXX.Models.test

<div class="jumbotron" style="background-color:white;opacity:.9">
    @Html.AntiForgeryToken()
    <style>
        th {
            color: black;
            font-size: 20px;
             background-color:#f2f2f2;
        }
    </style>
    <h3>Test Schedule :</h3>
    <p style="color:black;font-size:14px">We are conducting exams on topic wise for each week. Exams are conducting separately for General Tamil and General English.</p>
    <div class="form-horizontal">
        <div class="form-group">
         
            <div class="col-md-12">
                @{ if (ViewBag.admin == true)
                    {
                        <div class="form-group">
                            <h3>  To Add Test Subjects Click On Add Button @Html.ActionLink("Add", "addtest", "TestPlan")</h3>
                            <div class="col-md-offset-2 col-md-10 text-center">
                               
                            </div>
                        </div>
                    }
                }
                @{ if (ViewBag.getdata == true)
                    {
                <table id="tab_logic" class="table table-condensed table-hover">
                    <tr>
                        <th>
                            Subject
                        </th>
                        <th>
                            Date
                        </th>
                    </tr>
                    @{
                        //To make unique Id
                        int i = 0;
                        foreach (var item in Model.testDetails.ToList())
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(o => o.testDetails[i].testSub, new { @id = "testSub_" + i, @class = "form-control", @readonly = "readonly", @style = "background-color:white;border:none;border-radius:0px" })
                                    @Html.ValidationMessageFor(m => m.testDetails[i].testSub)
                                </td>
                                <td>
                                    @Html.DisplayFor(o => o.testDetails[i].testDate, new { @id = "testDate_" + i, @class = "form-control", @readonly = "readonly", @style = "background-color:white;border:none;border-radius:0px" })
                                    @Html.ValidationMessageFor(m => m.testDetails[i].testDate)
                                </td>
                            </tr>
                            i++;
                        }
                    }
                </table>
                        }
                        else
                        {
                            @Html.Label("No Record Found")
                        }
                }
            </div>
        </div>
        <hr />
    </div>
</div>

@*@using (Html.BeginForm("Subscribe", "TestPlan", FormMethod.Post))
    {
        <div>
            <table id="tab_logic">
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.id)
                    </td>
                    <td>
                    @Html.TextBoxFor(model => model.testSub)
                    </td>
                    <td>
                    @Html.TextBoxFor(model => model.testDate)
                     </td>
                </tr>

            </table>
            <button type="submit">Subscribe</button>
        </div>
    }*@
@*<a id="add_row" class="btn btn-default pull-left">Add Row</a>*@
@*<script type="text/javascript">
        $(document).ready(function () {

            $("#add_row").click(function () {
                //$('#addr' + i).html("<td>" + (i + 1) + "</td><td><input name='name" + i + "' type='text' placeholder='Name' class='form-control input-md'  /> </td><td><input  name='mail" + i + "' type='text' placeholder='Mail'  class='form-control input-md'></td><td><input  name='mobile" + i + "' type='text' placeholder='Mobile'  class='form-control input-md'></td>");



            });
            $("#delete_row").click(function () {
                if (i > 1) {
                    $("#addr" + (i - 1)).html('');
                    i--;
                }
            });

        });
    </script>*@

KMAXX/Views/Shared/_uploadFile.cshtml
@model KMAXX.Models.MyViewModel

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    @using (Html.BeginForm("Index", "currentAffairs", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            @Html.LabelFor(x => x.File)
            @Html.TextBoxFor(x => x.File, new { type = "file" })
            @Html.ValidationMessageFor(x => x.File)
        </div>
        <button type="submit">Upload File</button>
    }
</div>

<p>
    @Html.ActionLink("Download File", "Download")
</p>

KMAXX/Views/Shared/loginrequired.cshtml
<div class="jumbotron" style="background-color:antiquewhite;opacity:.9">
    <p style="color:black">Login required to view this page.  </p>
    <p>
        <div>
            If you have already signed in please login

            @*@{Html.RenderPartial("Login");}*@
            <button onclick="location.href='@Url.Action("Login","Login",new { returnUrl = ViewBag.returnUrl})'">Login </button>
        </div>
    </p>
    <p>
        <div>Don't have account sign in here <button onclick="location.href='@Url.Action("CreateLogin","Home" , new { returnUrl = ViewBag.returnUrl })'">Sign In </button></div>

    </p>
</div>